site_name: FEZdoc
site_description: Remote Sensing Python Tools
site_url: https://mhdned.github.io/FEZdoc/
site_author: mhdned
repo_url: https://github.com/mhdned/FEZdoc
repo_name: FEZdoc

nav:
  - Home: index.md
  - Libraries:
      - FEZrs:
          - Overview: libraries/fezrs/index.md
          - Change Detection: libraries/fezrs/change-detection.md
          - Clustering: libraries/fezrs/clustering.md
          - Filters: libraries/fezrs/filters.md
          - GLCM: libraries/fezrs/glcm.md
          - HSV: libraries/fezrs/hsv.md
          - Image Enhancement: libraries/fezrs/image-enhancement.md
          - Import Tools: libraries/fezrs/import-tools.md
          - Mosaic: libraries/fezrs/mosaic.md
          - PCA: libraries/fezrs/pca.md
          - Spectral Indices: libraries/fezrs/spectral-indices.md
          - Spectral Profile: libraries/fezrs/spectral-profile.md
          - SVM: libraries/fezrs/svm.md
      - FEZcc: libraries/fezcc.md
      - FEZsies: libraries/fezseis.md
  - Licenses: licenses.md
  - Stay in Touch: contact.md

theme:
  name: material

  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/white-balance-sunny
        name: Switch to light mode

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.instant
    - content.code.copy
    - search.highlight
    - search.share

markdown_extensions:
  - admonition

  - toc:
      permalink: true

  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search

extra_css:
  - styles/extra.css

extra_javascript:
  - javascript/extra.js

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mhdned

  generator: false
